# Generated by Django 5.1 on 2024-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Meat', 'Meat'), ('Other', 'Other'), ('Drinks', 'Drinks')], max_length=64, null=True),
        ),
    ]
