# Generated by Django 5.1 on 2024-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(blank=True, null=True, to='website.product'),
        ),
    ]
