# Generated by Django 5.1 on 2024-08-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_order_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(blank=True, to='website.product'),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.order')),
                ('order_list', models.ManyToManyField(blank=True, to='website.orderitem')),
            ],
        ),
    ]
